driver:
  name: vagrant
  customize:
    memory: 6144
    cpus: 4


provisioner:
  product_name: chef
  product_version: 13.8

verifier:
  name: inspec

platforms:
  - name: ubuntu/xenial64
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8000, auto_correct: true}]
      - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

suites:
  - name: default
    run_list: <%= node["run_list"] %>
